#!/usr/bin/env python3
"""Independent reconstruction checker for the canonical four-action payload.

The checker deliberately uses a different data path from the producer:
groups are generated by closure from generators, coordinate supports are
scanned by integer weight, and orbit-sum values are accumulated by enumerating
the support subsets contained in each pattern.  No producer module is imported
and no producer-generated separator mask is trusted.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import itertools
import json
import math
import sys
import time
from collections import defaultdict, deque
from dataclasses import dataclass
from io import StringIO
from pathlib import Path
from typing import Sequence


EXPERIMENT = (
    "FOUR_FIVE_VERTEX_ORBIT_SUM_RECONSTRUCTION"
)
PAYLOAD_SCHEMA = "orbit_sum_canonical_payload_v1"


def encoded(value: object) -> bytes:
    return (
        json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
        + "\n"
    ).encode("utf-8")


def digest_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def digest_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(1048576):
            h.update(block)
    return h.hexdigest()


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(encoded(value))


def compose(left: Sequence[int], right: Sequence[int]) -> tuple[int, ...]:
    """Return left after right."""
    return tuple(left[right[index]] for index in range(len(left)))


def generated_group(n: int, alternating: bool) -> tuple[tuple[int, ...], ...]:
    identity = tuple(range(n))
    if alternating:
        generators = []
        for k in range(2, n):
            cycle = list(range(n))
            cycle[0], cycle[1], cycle[k] = 1, k, 0
            generators.append(tuple(cycle))
    else:
        swap = list(range(n))
        swap[0], swap[1] = 1, 0
        long_cycle = tuple(list(range(1, n)) + [0])
        generators = [tuple(swap), long_cycle]
    group = {identity}
    queue = deque([identity])
    while queue:
        current = queue.popleft()
        for generator in generators:
            for candidate in (compose(generator, current), compose(current, generator)):
                if candidate not in group:
                    group.add(candidate)
                    queue.append(candidate)
    target = math.factorial(n) // (2 if alternating else 1)
    if len(group) != target:
        raise AssertionError(f"generator closure has {len(group)} elements, wanted {target}")
    return tuple(sorted(group))


def arcs_for(n: int) -> tuple[tuple[int, int], ...]:
    return tuple((tail, head) for tail in range(n) for head in range(n) if tail != head)


def action_maps(
    arcs: Sequence[tuple[int, int]], group: Sequence[Sequence[int]]
) -> tuple[tuple[int, ...], ...]:
    positions = {arc: index for index, arc in enumerate(arcs)}
    return tuple(
        tuple(positions[(permutation[i], permutation[j])] for i, j in arcs)
        for permutation in group
    )


def move(mask: int, mapping: Sequence[int]) -> int:
    result = 0
    for source, destination in enumerate(mapping):
        if mask & (1 << source):
            result |= 1 << destination
    return result


def canonical(mask: int, maps: Sequence[Sequence[int]]) -> int:
    return min(move(mask, mapping) for mapping in maps)


def full_orbit(mask: int, maps: Sequence[Sequence[int]]) -> tuple[int, ...]:
    return tuple(sorted({move(mask, mapping) for mapping in maps}))


def orbit_representatives(bit_count: int, maps: Sequence[Sequence[int]]) -> tuple[int, ...]:
    owners = [-1] * (1 << bit_count)
    representatives: list[int] = []
    for mask in range(1 << bit_count):
        if owners[mask] >= 0:
            continue
        orbit = full_orbit(mask, maps)
        representative = min(orbit)
        orbit_number = len(representatives)
        representatives.append(representative)
        for member in orbit:
            if owners[member] not in (-1, orbit_number):
                raise AssertionError("overlapping group orbits")
            owners[member] = orbit_number
    if any(owner < 0 for owner in owners):
        raise AssertionError("pattern partition incomplete")
    return tuple(sorted(representatives))


@dataclass(frozen=True)
class IndependentCoordinate:
    degree: int
    representative: int
    members: tuple[int, ...]


@dataclass
class IndependentModel:
    n: int
    name: str
    arcs: tuple[tuple[int, int], ...]
    group: tuple[tuple[int, ...], ...]
    maps: tuple[tuple[int, ...], ...]
    patterns: tuple[int, ...]
    coordinates: tuple[IndependentCoordinate, ...]
    matrix: tuple[tuple[int, ...], ...]

    @property
    def hex_width(self) -> int:
        return math.ceil(len(self.arcs) / 4)

    def pid(self, pattern: int) -> str:
        return f"{self.name}:{self.n}:{pattern:0{self.hex_width}x}"

    def cid(self, coordinate: IndependentCoordinate) -> str:
        return (
            f"{self.name}:{self.n}:{coordinate.degree}:"
            f"{coordinate.representative:0{self.hex_width}x}"
        )


def independent_coordinates(
    bit_count: int, maximum_degree: int, maps: Sequence[Sequence[int]]
) -> tuple[tuple[IndependentCoordinate, ...], dict[int, int]]:
    coordinates: list[IndependentCoordinate] = []
    support_to_index: dict[int, int] = {}
    for degree in range(1, maximum_degree + 1):
        representatives: dict[int, tuple[int, ...]] = {}
        for support in range(1, 1 << bit_count):
            if support.bit_count() != degree:
                continue
            representative = canonical(support, maps)
            if representative not in representatives:
                representatives[representative] = full_orbit(representative, maps)
        for representative in sorted(representatives):
            index = len(coordinates)
            members = representatives[representative]
            coordinates.append(IndependentCoordinate(degree, representative, members))
            for support in members:
                if support in support_to_index:
                    raise AssertionError("support belongs to two coordinate orbits")
                support_to_index[support] = index
    return tuple(coordinates), support_to_index


def contained_support_signature(
    pattern: int,
    coordinates: Sequence[IndependentCoordinate],
    support_to_index: dict[int, int],
    maximum_degree: int,
) -> tuple[int, ...]:
    selected_bits = [index for index in range(pattern.bit_length()) if pattern & (1 << index)]
    values = [0] * len(coordinates)
    for degree in range(1, min(maximum_degree, len(selected_bits)) + 1):
        for subset in itertools.combinations(selected_bits, degree):
            support = sum(1 << index for index in subset)
            values[support_to_index[support]] += 1
    return tuple(values)


def reconstruct_model(n: int, alternating: bool) -> IndependentModel:
    name = f"{'A' if alternating else 'S'}{n}"
    arcs = arcs_for(n)
    group = generated_group(n, alternating)
    maps = action_maps(arcs, group)
    patterns = orbit_representatives(len(arcs), maps)
    coordinates, support_to_index = independent_coordinates(len(arcs), n - 1, maps)
    matrix = tuple(
        contained_support_signature(pattern, coordinates, support_to_index, n - 1)
        for pattern in patterns
    )
    if len(set(matrix)) != len(matrix):
        raise AssertionError(f"top degree is noninjective for {name}")
    return IndependentModel(n, name, arcs, group, maps, patterns, coordinates, matrix)


def graph_class(model: IndependentModel, support: int) -> dict[str, object]:
    directed = [
        model.arcs[index]
        for index in range(len(model.arcs))
        if support & (1 << index)
    ]
    edges = {tuple(sorted(edge)) for edge in directed}
    touched = {vertex for edge in edges for vertex in edge}
    neighbors = {vertex: set() for vertex in touched}
    for left, right in edges:
        neighbors[left].add(right)
        neighbors[right].add(left)
    visited: set[int] = set()
    frontier = list(touched)[:1]
    while frontier:
        vertex = frontier.pop()
        if vertex in visited:
            continue
        visited.add(vertex)
        frontier.extend(neighbors[vertex] - visited)
    connected = bool(touched) and visited == touched
    tree = connected and len(touched) == model.n and len(edges) == model.n - 1
    unicyclic = connected and len(edges) == len(touched)
    incoming = [0] * model.n
    outgoing = [0] * model.n
    undirected_degrees = [0] * model.n
    for left, right in directed:
        outgoing[left] += 1
        incoming[right] += 1
    for left, right in edges:
        undirected_degrees[left] += 1
        undirected_degrees[right] += 1
    category = (
        "TREE_ON_ALL_VERTICES"
        if tree
        else "UNICYCLIC_ON_TOUCHED_VERTICES"
        if unicyclic
        else "OTHER"
    )
    return {
        "category": category,
        "connected_on_touched_vertices": connected,
        "directed_arc_count": len(directed),
        "indegree_sequence": sorted(incoming, reverse=True),
        "outdegree_sequence": sorted(outgoing, reverse=True),
        "touched_vertex_count": len(touched),
        "undirected_degree_sequence": sorted(undirected_degrees, reverse=True),
        "undirected_edge_count": len(edges),
    }


def collision_pairs(model: IndependentModel, through_degree: int) -> tuple[tuple[int, int], ...]:
    prefix = sum(c.degree <= through_degree for c in model.coordinates)
    blocks: dict[tuple[int, ...], list[int]] = defaultdict(list)
    for pattern_index, signature in enumerate(model.matrix):
        blocks[signature[:prefix]].append(pattern_index)
    ordered_blocks = sorted(blocks.values(), key=lambda block: block[0])
    return tuple(
        pair
        for block in ordered_blocks
        for pair in itertools.combinations(block, 2)
    )


def top_separators(
    model: IndependentModel, pairs: Sequence[tuple[int, int]]
) -> tuple[list[int], list[dict[str, object]], list[dict[str, object]], list[int]]:
    top_indices = [
        index for index, coordinate in enumerate(model.coordinates)
        if coordinate.degree == model.n - 1
    ]
    per_coordinate = [0] * len(top_indices)
    pair_rows: list[dict[str, object]] = []
    for pair_index, (left, right) in enumerate(pairs):
        local_separators = [
            local
            for local, global_index in enumerate(top_indices)
            if model.matrix[left][global_index] != model.matrix[right][global_index]
        ]
        for local in local_separators:
            per_coordinate[local] |= 1 << pair_index
        left_id = model.pid(model.patterns[left])
        right_id = model.pid(model.patterns[right])
        pair_rows.append(
            {
                "pair_id": [left_id, right_id],
                "pattern_indices": [left, right],
                "separator_coordinate_ids": [
                    model.cid(model.coordinates[top_indices[local]])
                    for local in local_separators
                ],
                "separator_local_mask_hex": f"{sum(1 << local for local in local_separators):0{max(1, math.ceil(len(top_indices) / 4))}x}",
            }
        )
    pair_hex_width = max(1, math.ceil(len(pairs) / 4))
    coordinate_rows = [
        {
            "coordinate_id": model.cid(model.coordinates[global_index]),
            "separated_pair_mask_hex": f"{bits:0{pair_hex_width}x}",
        }
        for global_index, bits in zip(top_indices, per_coordinate)
    ]
    return per_coordinate, pair_rows, coordinate_rows, top_indices


def exact_covers(
    masks: Sequence[int], universe_size: int, candidate_indices: Sequence[int]
) -> tuple[int | None, tuple[tuple[int, ...], ...]]:
    target = (1 << universe_size) - 1
    candidates = tuple(candidate_indices)
    aggregate = 0
    for candidate in candidates:
        aggregate |= masks[candidate]
    if aggregate != target:
        return None, ()
    if target == 0:
        return 0, ((),)
    for cardinality in range(1, len(candidates) + 1):
        winners = []
        for subset in itertools.combinations(candidates, cardinality):
            union = 0
            for candidate in subset:
                union |= masks[candidate]
            if union == target:
                winners.append(subset)
        if winners:
            return cardinality, tuple(winners)
    raise AssertionError("cover enumeration failed")


def raw_transform_map(
    arcs: Sequence[tuple[int, int]], vertex_permutation: Sequence[int] | None
) -> tuple[int, ...]:
    positions = {arc: index for index, arc in enumerate(arcs)}
    if vertex_permutation is None:
        return tuple(positions[(head, tail)] for tail, head in arcs)
    return tuple(
        positions[(vertex_permutation[tail], vertex_permutation[head])]
        for tail, head in arcs
    )


def outside_coordinate_actions(
    model: IndependentModel, top_indices: Sequence[int]
) -> tuple[tuple[int, ...], ...]:
    by_representative = {
        model.coordinates[global_index].representative: local
        for local, global_index in enumerate(top_indices)
    }
    raw_generators = [raw_transform_map(model.arcs, None)]
    if model.name.startswith("A"):
        odd = tuple([1, 0] + list(range(2, model.n)))
        raw_generators.append(raw_transform_map(model.arcs, odd))
    actions = []
    for raw in raw_generators:
        action = []
        for global_index in top_indices:
            transformed = move(model.coordinates[global_index].representative, raw)
            action.append(by_representative[canonical(transformed, model.maps)])
        if len(set(action)) != len(action):
            raise AssertionError("external map is not bijective")
        actions.append(tuple(action))
    return tuple(actions)


def quotient_solutions(
    solutions: Sequence[tuple[int, ...]], actions: Sequence[Sequence[int]]
) -> tuple[tuple[tuple[int, ...], ...], ...]:
    allowed = {tuple(solution) for solution in solutions}
    remaining = set(allowed)
    answer = []
    while remaining:
        seed = min(remaining)
        orbit = {seed}
        queue = deque([seed])
        while queue:
            solution = queue.popleft()
            for action in actions:
                image = tuple(sorted(action[index] for index in solution))
                if image not in allowed:
                    raise AssertionError("external image is not an optimal solution")
                if image not in orbit:
                    orbit.add(image)
                    queue.append(image)
        remaining -= orbit
        answer.append(tuple(sorted(orbit)))
    return tuple(sorted(answer))


def subgroup_crosswalk(
    alternating: IndependentModel, symmetric: IndependentModel
) -> tuple[dict[int, int], list[dict[str, object]]]:
    symmetric_index = {pattern: index for index, pattern in enumerate(symmetric.patterns)}
    mapping = {}
    fibres: dict[int, list[int]] = defaultdict(list)
    for a_index, pattern in enumerate(alternating.patterns):
        parent = canonical(pattern, symmetric.maps)
        s_index = symmetric_index[parent]
        mapping[a_index] = s_index
        fibres[s_index].append(a_index)
    rows = []
    for s_index in sorted(fibres):
        children = fibres[s_index]
        if len(children) not in (1, 2):
            raise AssertionError("subgroup fibre size is not one or two")
        rows.append(
            {
                "S_orbit_id": symmetric.pid(symmetric.patterns[s_index]),
                "A_orbit_ids": [alternating.pid(alternating.patterns[i]) for i in children],
                "splits": len(children) == 2,
            }
        )
    return mapping, rows


def metadata(model: IndependentModel) -> list[dict[str, object]]:
    return [
        {
            "coordinate_id": model.cid(coordinate),
            "degree": coordinate.degree,
            "orbit_size": len(coordinate.members),
            "representative_hex": f"{coordinate.representative:0{model.hex_width}x}",
            "support_class": graph_class(model, coordinate.representative),
        }
        for coordinate in model.coordinates
    ]


def reconstruct_a5_signed_matrix(
    symmetric: IndependentModel, alternating: IndependentModel
) -> bytes:
    """Reconstruct the signed split-parent matrix from the group actions."""

    symmetric_patterns = set(symmetric.patterns)
    alternating_pattern_index = {
        mask: index for index, mask in enumerate(alternating.patterns)
    }
    split_rows: list[tuple[int, int, int]] = []
    for left, right in collision_pairs(alternating, 3):
        left_mask = alternating.patterns[left]
        right_mask = alternating.patterns[right]
        left_parent = canonical(left_mask, symmetric.maps)
        right_parent = canonical(right_mask, symmetric.maps)
        if left_parent == right_parent:
            if left_parent not in symmetric_patterns:
                raise AssertionError("split-pattern parent absent from the symmetric registry")
            first, second = sorted((left_mask, right_mask))
            split_rows.append((first, second, left_parent))
    split_rows.sort()
    if len(split_rows) != 54:
        raise AssertionError(f"signed matrix has {len(split_rows)} rows, wanted 54")

    symmetric_quartics = {
        coordinate.representative
        for coordinate in symmetric.coordinates
        if coordinate.degree == 4
    }
    split_supports: dict[int, list[int]] = defaultdict(list)
    for index, coordinate in enumerate(alternating.coordinates):
        if coordinate.degree != 4:
            continue
        parent = canonical(coordinate.representative, symmetric.maps)
        if parent not in symmetric_quartics:
            raise AssertionError("split-support parent absent from the symmetric registry")
        split_supports[parent].append(index)
    split_supports = {
        parent: sorted(
            children,
            key=lambda index: alternating.coordinates[index].representative,
        )
        for parent, children in split_supports.items()
        if len(children) == 2
    }
    parents = sorted(split_supports)
    if len(parents) != 35:
        raise AssertionError(f"signed matrix has {len(parents)} columns, wanted 35")

    rows: list[list[object]] = []
    for first_mask, second_mask, parent in split_rows:
        first_index = alternating_pattern_index[first_mask]
        second_index = alternating_pattern_index[second_mask]
        values: list[int] = []
        for support_parent in parents:
            plus, minus = split_supports[support_parent]
            first_value = (
                alternating.matrix[first_index][plus]
                - alternating.matrix[first_index][minus]
            )
            second_value = (
                alternating.matrix[second_index][plus]
                - alternating.matrix[second_index][minus]
            )
            if first_value != -second_value:
                raise AssertionError("signed-channel anti-invariance failed")
            values.append(first_value)
        rows.append(
            [f"{first_mask:05x}", f"{second_mask:05x}", f"{parent:05x}", *values]
        )

    stream = StringIO(newline="")
    writer = csv.writer(stream, lineterminator="\n")
    writer.writerow(
        ["a5_pattern_1", "a5_pattern_2", "s5_parent"]
        + [f"{parent:05x}" for parent in parents]
    )
    writer.writerows(rows)
    return stream.getvalue().encode("utf-8")


def reconstruct_group_payload(
    model: IndependentModel, symmetric_companion: IndependentModel | None
) -> dict[str, object]:
    pairs = collision_pairs(model, model.n - 2)
    cover_masks, pair_rows, coordinate_rows, top_indices = top_separators(model, pairs)
    tree_locals = [
        local
        for local, global_index in enumerate(top_indices)
        if graph_class(model, model.coordinates[global_index].representative)["category"]
        == "TREE_ON_ALL_VERTICES"
    ]
    tree_union = 0
    for local in tree_locals:
        tree_union |= cover_masks[local]
    tree_blind = [index for index in range(len(pairs)) if not (tree_union >> index) & 1]

    extension_minimum, extension_solutions = exact_covers(
        cover_masks, len(pairs), range(len(top_indices))
    )
    tree_minimum, tree_solutions = exact_covers(
        cover_masks, len(pairs), tree_locals
    )
    actions = outside_coordinate_actions(model, top_indices)
    external_orbits = quotient_solutions(extension_solutions, actions)

    crosswalk = []
    index_two_split_pairs = []
    parent_mapping: dict[int, int] = {}
    if model.name.startswith("A"):
        if symmetric_companion is None:
            raise ValueError("missing symmetric companion")
        parent_mapping, crosswalk = subgroup_crosswalk(model, symmetric_companion)
        index_two_split_pairs = [
            pair_index
            for pair_index, (left, right) in enumerate(pairs)
            if parent_mapping[left] == parent_mapping[right]
        ]

    split_pair_set = set(index_two_split_pairs)
    blind_set = set(tree_blind)
    for pair_index, row in enumerate(pair_rows):
        row["index_two_split_pair"] = pair_index in split_pair_set
        row["tree_blind"] = pair_index in blind_set
        if model.name.startswith("A"):
            left, right = pairs[pair_index]
            row["S_parent_orbit_ids"] = [
                symmetric_companion.pid(
                    symmetric_companion.patterns[parent_mapping[left]]
                ),
                symmetric_companion.pid(
                    symmetric_companion.patterns[parent_mapping[right]]
                ),
            ]

    shape_counts: dict[str, int] = defaultdict(int)
    solution_rows = []
    for solution in extension_solutions:
        categories = sorted(
            graph_class(model, model.coordinates[top_indices[local]].representative)[
                "category"
            ]
            for local in solution
        )
        shape_counts["+".join(categories)] += 1
        solution_rows.append(
            {
                "coordinate_ids": [
                    model.cid(model.coordinates[top_indices[local]]) for local in solution
                ],
                "support_categories": categories,
            }
        )

    profile = [
        sum(coordinate.degree == degree for coordinate in model.coordinates)
        for degree in range(1, model.n)
    ]
    return {
        "group": model.name,
        "n": model.n,
        "arc_count": len(model.arcs),
        "arc_order": [list(arc) for arc in model.arcs],
        "group_order": len(model.group),
        "pattern_orbit_count": len(model.patterns),
        "pattern_orbit_ids": [model.pid(pattern) for pattern in model.patterns],
        "coordinate_profile_degrees_1_to_top": profile,
        "coordinate_metadata": metadata(model),
        "residual_degree": model.n - 2,
        "residual_pair_count": len(pairs),
        "residual_pairs": pair_rows,
        "top_degree_pair_by_coordinate_separation_bitsets": coordinate_rows,
        "top_degree_tree_coordinate_count": len(tree_locals),
        "pairs_with_a_tree_separator": tree_union.bit_count(),
        "tree_blind_pair_indices": tree_blind,
        "tree_blind_pair_count": len(tree_blind),
        "index_two_split_pair_indices": index_two_split_pairs,
        "index_two_split_pair_count": len(index_two_split_pairs),
        "all_tree_blind_pairs_are_index_two_split_pairs": all(
            pair in split_pair_set for pair in tree_blind
        ),
        "Sn_to_An_split_crosswalk": crosswalk,
        "conditional_top_degree_extension": {
            "minimum": extension_minimum,
            "solution_count_before_external_quotient": len(extension_solutions),
            "solutions": solution_rows,
            "external_generator_coordinate_maps": [list(action) for action in actions],
            "external_orbit_count": len(external_orbits),
            "external_orbits_as_solution_indices": [
                [extension_solutions.index(solution) for solution in orbit]
                for orbit in external_orbits
            ],
            "support_shape_census": dict(sorted(shape_counts.items())),
        },
        "tree_only_cover": {
            "minimum": tree_minimum,
            "solution_count": len(tree_solutions),
            "solutions": [
                [model.cid(model.coordinates[top_indices[local]]) for local in solution]
                for solution in tree_solutions
            ],
        },
    }


def comparisons(groups: dict[str, dict[str, object]]) -> list[dict[str, object]]:
    expected = {
        "S4": {
            "residual_pair_count": 39,
            "pairs_with_a_tree_separator": 39,
        },
        "A4": {
            "residual_pair_count": 51,
            "index_two_split_pair_count": 9,
            "pairs_with_a_tree_separator": 51,
        },
        "S5": {
            "pattern_orbit_count": 9608,
            "coordinate_profile_degrees_1_to_top": [1, 5, 16, 61],
            "residual_pair_count": 190,
            "pairs_with_a_tree_separator": 190,
            "top_degree_tree_coordinate_count": 27,
            "tree_only_cover.minimum": 5,
            "tree_only_cover.solution_count": 88,
            "conditional_top_degree_extension.minimum": 4,
            "conditional_top_degree_extension.solution_count_before_external_quotient": 2,
            "conditional_top_degree_extension.external_orbit_count": 1,
        },
        "A5": {
            "pattern_orbit_count": 17824,
            "coordinate_profile_degrees_1_to_top": [1, 6, 21, 96],
            "residual_pair_count": 113,
            "index_two_split_pair_count": 54,
            "tree_blind_pair_count": 8,
            "all_tree_blind_pairs_are_index_two_split_pairs": True,
            "conditional_top_degree_extension.minimum": 4,
            "conditional_top_degree_extension.solution_count_before_external_quotient": 200,
            "conditional_top_degree_extension.external_orbit_count": 50,
        },
    }

    def get(source: object, dotted: str) -> object:
        current = source
        for key in dotted.split("."):
            if not isinstance(current, dict):
                raise KeyError(dotted)
            current = current[key]
        return current

    rows = []
    for group_name, fields in expected.items():
        for field, target in fields.items():
            observed = get(groups[group_name], field)
            rows.append(
                {
                    "group": group_name,
                    "field": field,
                    "expected": target,
                    "observed": observed,
                    "pass": observed == target,
                }
            )
    return rows


def locate_root(explicit: str | None) -> Path:
    return Path(explicit).resolve() if explicit else Path(__file__).resolve().parents[3]


def run(project_root: Path, producer_dir: Path, output_dir: Path) -> int:
    started = time.perf_counter()
    specification = project_root / "schemas" / "five_vertex_specification.json"
    normalization = project_root / "docs" / "NORMALIZATION_LOCK.md"
    producer_payload = producer_dir / "canonical_payload.json"
    spec = json.loads(specification.read_text(encoding="utf-8"))
    if spec.get("specification_id") != EXPERIMENT:
        raise ValueError("wrong five-vertex specification")
    if "Squarefree orbit-sum coordinates" not in normalization.read_text(encoding="utf-8"):
        raise ValueError("normalization marker absent")
    producer_raw = producer_payload.read_bytes()
    producer_object = json.loads(producer_raw)
    if encoded(producer_object) != producer_raw:
        raise ValueError("producer payload is not canonical JSON with trailing LF")
    if producer_object.get("schema") != PAYLOAD_SCHEMA:
        raise ValueError("unexpected producer payload schema")

    models = {
        "S4": reconstruct_model(4, False),
        "A4": reconstruct_model(4, True),
        "S5": reconstruct_model(5, False),
        "A5": reconstruct_model(5, True),
    }
    signed_matrix = reconstruct_a5_signed_matrix(models["S5"], models["A5"])
    distributed_matrix = (
        project_root / "certificates" / "structural" / "a5_signed_matrix.csv"
    )
    if not distributed_matrix.is_file():
        raise FileNotFoundError(f"missing signed structural matrix: {distributed_matrix}")
    if signed_matrix != distributed_matrix.read_bytes():
        raise AssertionError("independent signed A5 matrix differs from the certificate")
    groups = {
        "S4": reconstruct_group_payload(models["S4"], None),
        "A4": reconstruct_group_payload(models["A4"], models["S4"]),
        "S5": reconstruct_group_payload(models["S5"], None),
        "A5": reconstruct_group_payload(models["A5"], models["S5"]),
    }
    target_rows = comparisons(groups)
    verdict = (
        "PASS_FIVE_VERTEX_CANONICAL_TARGETS"
        if all(row["pass"] for row in target_rows)
        else "FAIL_FIVE_VERTEX_SCIENTIFIC_DISAGREEMENT"
    )
    rebuilt = {
        "schema": PAYLOAD_SCHEMA,
        "experiment_id": EXPERIMENT,
        "phase": "CANONICAL_PAYLOAD",
        "scope": {"n_values": [4, 5], "n_greater_than_5_executed": False},
        "serialization": spec["canonical_serialization"],
        "groups": groups,
        "target_comparisons": target_rows,
        "verdict": verdict,
    }
    rebuilt_raw = encoded(rebuilt)
    byte_identical = rebuilt_raw == producer_raw
    output_dir.mkdir(parents=True, exist_ok=True)
    rebuilt_path = output_dir / "reconstructed_payload.json"
    rebuilt_path.write_bytes(rebuilt_raw)
    (output_dir / "a5_signed_matrix.csv").write_bytes(signed_matrix)
    verdict_name = (
        "PASS_FIVE_VERTEX_PAYLOAD_RECONSTRUCTION"
        if byte_identical and verdict.startswith("PASS")
        else "FAIL_FIVE_VERTEX_PAYLOAD_RECONSTRUCTION"
    )
    elapsed = round(time.perf_counter() - started, 6)
    print(
        f"ORBIT_SUM_CHECKER_{verdict_name}|bytes={len(rebuilt_raw)}|"
        f"sha256={digest_bytes(rebuilt_raw)}|seconds={elapsed}"
    )
    return 0 if verdict_name.startswith("PASS") else 2


def arguments(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root")
    parser.add_argument("--producer")
    parser.add_argument("--output")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = arguments(sys.argv[1:] if argv is None else argv)
    root = locate_root(args.project_root)
    producer = Path(args.producer).resolve() if args.producer else root / "certificates" / "five_vertex"
    output = Path(args.output).resolve() if args.output else root / "tmp" / "five_vertex_checker"
    return run(root, producer, output)


if __name__ == "__main__":
    raise SystemExit(main())
